services:
  redis:
    image: redis:7-alpine
    container_name: imagelab-redis
    restart: always
    command: ["redis-server", "--appendonly", "yes"]
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: imagelab-backend
    restart: always
    env_file: .env
    depends_on:
      - redis
    ports:
      - "5000:5000"
    volumes:
      - uploads_data:/app/uploads
      - db_data:/app/instance

  frontend:
    build: ./frontend
    container_name: imagelab-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: imagelab-prometheus
    restart: always
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.retention.time=15d"
      - "--storage.tsdb.retention.size=5GB"
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    depends_on:
      - backend

  node-exporter:
    image: prom/node-exporter
    container_name: imagelab-node-exporter
    restart: always
    pid: host
    command:
      - "--path.rootfs=/host"
    volumes:
      - /:/host:ro,rslave
    expose:
      - "9100"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: imagelab-cadvisor
    restart: always
    privileged: true
    devices:
      - /dev/kmsg
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - "8080"

  grafana:
    image: grafana/grafana
    container_name: imagelab-grafana
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

  loki:
    image: grafana/loki:3.7.0
    container_name: imagelab-loki
    restart: always
    command:
      - "-config.file=/etc/loki/local-config.yaml"
    ports:
      - "127.0.0.1:3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yml:/etc/loki/local-config.yaml:ro
      - loki_data:/loki

  promtail:
    image: grafana/promtail:2.9.10
    container_name: imagelab-promtail
    restart: always
    user: "0"
    command:
      - "-config.file=/etc/promtail/config.yml"
    volumes:
      - ./monitoring/promtail/promtail.yml:/etc/promtail/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

volumes:
  redis_data:
  uploads_data:
  db_data:
  prometheus_data:
  grafana_data:
  loki_data:
